### ISSUE TITLE
Fix footer

### ISSUE THREAD

**Issue by rhvsingh** [rhvsingh/website_repo_3#7]
1. Fix copyright section font size, color, and alignments.
2. Fix form padding and margin.
3. Fix text font size and color

**Comment by ashutosh7i** [comment]
can i fix this issue?

**Comment by rhvsingh** [comment]
Go ahead @ashutosh7i

**Comment by RockingRishav** [comment]
Can I also work upon this issue?

**Comment by rhvsingh** [comment]
> Can I also work upon this issue?

Ask @ashutosh7i if he is okay with it, then np. Otherwise, look for other issues or create a new one.
